version: 1.0.{build}

# Use Ubuntu image
image: Ubuntu2004

# Basic environment
environment:
  CMAKE_BUILD_TYPE: Release
  INSTALL_PREFIX: install

# Install dependencies including CUDA toolkit (nvcc)
install:
  - sudo apt-get update -y
  - sudo apt-get install -y build-essential cmake git nvidia-cuda-toolkit

# Build
build_script:
  - echo "=== Building cuSZp on Ubuntu ==="
  - cmake -S . -B build -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}
  - cmake --build build -- -j"$(nproc)"
  - cmake --install build
