name: cuSZp codecov report

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.2.0-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get install -y cmake g++ make gcovr lcov git curl

      - name: Build with coverage
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
                   -DCMAKE_CXX_FLAGS="--coverage" \
                   -DCMAKE_CUDA_FLAGS="-Xcompiler --coverage" \
                   -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
                   -DCMAKE_SHARED_LINKER_FLAGS="--coverage"
          make -j$(nproc) && make install

      - name: Run tests
        run: |
          cd build
          ctest -V || true

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/
          flags: unittests
          name: cuSZp
          fail_ci_if_error: true
          exclude: |
            src/cuSZp.cu
            cmake/*
            install/*
            python/*

